import { Countries } from "../redux/country/types";

export const options = ["Africa", "America", "Asia", "Europe", "Oceania"];

const dummy: Countries = [
  {
    name: "Republic of Moldova",
    population: 2617820,
    region: "Europe",
    capital: ["Chișinău"],
    flags: `https://flagcdn.com/w320/md.png`,
    naiveName: "United States of America",
    currencies: ["Moldovan leu", "Rupee"],
    subregion: "Eastern Europe",
    languages: ["Hindi", "English"],
    tld: [".md", ".md13213"],
    borders: ["FRA", "DEU", "LUX", "NLD"],
  },
  {
    name: "United States of America",
    population: 329484123,
    region: "Americas",
    capital: ["Washington, D.C."],
    flags: `https://flagcdn.com/w320/md.png`,
    naiveName: "United States of America",
    currencies: ["Moldovan leu", "Rupee"],
    subregion: "Eastern Europe",
    languages: ["Hindi", "English"],
    tld: [".md", ".md13213"],
    borders: ["FRA", "DEU", "LUX", "NLD"],
  },
  {
    name: "123123",
    population: 2617820,
    region: "Europe",
    capital: ["Chișinău"],
    flags: `https://flagcdn.com/w320/md.png`,
    naiveName: "United States of America",
    currencies: ["Moldovan leu", "Rupee"],
    subregion: "Eastern Europe",
    languages: ["Hindi", "English"],
    tld: [".md", ".md13213"],
    borders: ["FRA", "DEU", "LUX", "NLD"],
  },
  {
    name: "aasdsad",
    population: 329484123,
    region: "Americas",
    capital: ["Washington, D.C."],
    flags: `https://flagcdn.com/w320/md.png`,
    naiveName: "United States of America",
    currencies: ["Moldovan leu", "Rupee"],
    subregion: "Eastern Europe",
    languages: ["Hindi", "English"],
    tld: [".md", ".md13213"],
    borders: ["FRA", "DEU", "LUX", "NLD"],
  },
  {
    name: "vxvxcvxcv",
    population: 2617820,
    region: "Europe",
    capital: ["Chișinău"],
    flags: `https://flagcdn.com/w320/md.png`,
    naiveName: "United States of America",
    currencies: ["Moldovan leu", "Rupee"],
    subregion: "Eastern Europe",
    languages: ["Hindi", "English"],
    tld: [".md", ".md13213"],
    borders: ["FRA", "DEU", "LUX", "NLD"],
  },
  {
    name: "Unierererera",
    population: 329484123,
    region: "Americas",
    capital: ["Washington, D.C."],
    flags: `https://flagcdn.com/w320/md.png`,
    naiveName: "United States of America",
    currencies: ["Moldovan leu", "Rupee"],
    subregion: "Eastern Europe",
    languages: ["Hindi", "English"],
    tld: [".md", ".md13213"],
    borders: ["FRA", "DEU", "LUX", "NLD"],
  },
];
